/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import data.StaticData;

/**
 *
 * @author Acer
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminLogbtn = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bookbtn = new javax.swing.JButton();
        cancelFlightBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 102)));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(null);

        adminLogbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminLogbtn.setText("Login as Admin");
        adminLogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogbtnActionPerformed(evt);
            }
        });
        add(adminLogbtn);
        adminLogbtn.setBounds(40, 600, 213, 48);
        add(logo1);
        logo1.setBounds(170, 120, 500, 360);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        bookbtn.setBackground(new java.awt.Color(255, 0, 0));
        bookbtn.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        bookbtn.setText("Book New Flight");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookbtn);
        bookbtn.setBounds(10, 90, 364, 91);

        cancelFlightBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cancelFlightBtn.setText("Cancel Flight");
        cancelFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFlightBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelFlightBtn);
        cancelFlightBtn.setBounds(60, 210, 264, 68);

        add(jPanel1);
        jPanel1.setBounds(810, 130, 390, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogbtnActionPerformed
        // TODO add your handling code here:
        AdminLogin adminLog = new AdminLogin(StaticData.frame, true);
        adminLog.setVisible(true);
        if(adminLog.getReturnStatus() == 1) {
            AdminPanel admin = new AdminPanel();
            StaticData.frame.add(admin);
            admin.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_adminLogbtnActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
        SignupPanel signup = new SignupPanel();
        StaticData.frame.add(signup);
        signup.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bookbtnActionPerformed

    private void cancelFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFlightBtnActionPerformed
        // TODO add your handling code here:
        CancelFlightDialog cancel = new CancelFlightDialog(data.StaticData.frame, true);
        cancel.setVisible(true);
    }//GEN-LAST:event_cancelFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLogbtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton cancelFlightBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
