/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import data.StaticData;

/**
 *
 * @author Acer
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookbtn = new javax.swing.JButton();
        adminLogbtn = new javax.swing.JButton();
        cancelFlightBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 102)));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        bookbtn.setBackground(java.awt.Color.green);
        bookbtn.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        bookbtn.setText("Book New Flight");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        adminLogbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminLogbtn.setText("Login as Admin");
        adminLogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogbtnActionPerformed(evt);
            }
        });

        cancelFlightBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cancelFlightBtn.setText("Cancel Flight");
        cancelFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(adminLogbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1073, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(473, 473, 473))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(528, 528, 528))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cancelFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(adminLogbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminLogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogbtnActionPerformed
        // TODO add your handling code here:
        AdminLogin adminLog = new AdminLogin(StaticData.frame, true);
        adminLog.setVisible(true);
        if(adminLog.getReturnStatus() == 1) {
            AdminPanel admin = new AdminPanel();
            StaticData.frame.add(admin);
            admin.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_adminLogbtnActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
        SignupPanel signup = new SignupPanel();
        StaticData.frame.add(signup);
        signup.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bookbtnActionPerformed

    private void cancelFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFlightBtnActionPerformed
        // TODO add your handling code here:
        CancelFlightDialog cancel = new CancelFlightDialog(data.StaticData.frame, true);
        cancel.setVisible(true);
    }//GEN-LAST:event_cancelFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLogbtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton cancelFlightBtn;
    // End of variables declaration//GEN-END:variables
}
