/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Acer
 */
public class SignupPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupPanel
     */
    public SignupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        flightDestinationLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        destinationBox = new javax.swing.JComboBox<>();
        ticketBtn = new javax.swing.JButton();
        firstNameStatusLabel = new javax.swing.JLabel();
        lastNameStatusLabel = new javax.swing.JLabel();
        flightDestinationStatusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 255));
        setLayout(null);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(50, 600, 168, 43);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)), "Ticket"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Ticket");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 30, 227, 31);

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name         :");
        jPanel1.add(firstNameLabel);
        firstNameLabel.setBounds(150, 190, 144, 22);

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name         :");
        jPanel1.add(lastNameLabel);
        lastNameLabel.setBounds(150, 240, 143, 22);

        flightDestinationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        flightDestinationLabel.setText("Flight Destination:");
        jPanel1.add(flightDestinationLabel);
        flightDestinationLabel.setBounds(150, 290, 143, 22);

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameField);
        firstNameField.setBounds(310, 190, 318, 26);
        jPanel1.add(lastNameField);
        lastNameField.setBounds(310, 240, 319, 26);

        data.PlaneSchedule[] plane = new data.PlaneSchedule[data.StaticData.planeData.size()];
        for(int i = 0; i < plane.length; i++) {
            plane[i] = (data.PlaneSchedule) data.StaticData.planeData.search(i);
        }
        javax.swing.DefaultComboBoxModel<String> flightBoxModel = new javax.swing.DefaultComboBoxModel<>();
        flightBoxModel.addElement("Choose your destination");
        for(int i = 0; i < data.StaticData.planeData.size(); i++) {
            flightBoxModel.addElement(plane[i].getDestination());
        }
        destinationBox.setModel(flightBoxModel);
        destinationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationBoxActionPerformed(evt);
            }
        });
        jPanel1.add(destinationBox);
        destinationBox.setBounds(310, 290, 319, 26);

        ticketBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ticketBtn.setText("Get Your Ticket");
        ticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ticketBtn);
        ticketBtn.setBounds(410, 400, 232, 60);
        jPanel1.add(firstNameStatusLabel);
        firstNameStatusLabel.setBounds(650, 190, 315, 26);
        jPanel1.add(lastNameStatusLabel);
        lastNameStatusLabel.setBounds(650, 240, 315, 26);
        jPanel1.add(flightDestinationStatusLabel);
        flightDestinationStatusLabel.setBounds(650, 290, 315, 26);

        add(jPanel1);
        jPanel1.setBounds(200, 40, 990, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        data.StaticData.loginPanel.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ticketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBtnActionPerformed
        // TODO add your handling code here:
        int indexComboBox = destinationBox.getSelectedIndex();
        firstNameStatusLabel.setText("");
        lastNameStatusLabel.setText("");
        flightDestinationStatusLabel.setText("");
        if(firstNameField.getText().isEmpty()) {
            firstNameStatusLabel.setText("Field cannot be empty");
            throw new EmptyFieldException();
        }
        if(lastNameField.getText().isEmpty()) {
            lastNameStatusLabel.setText("Field cannot be empty");
            throw new EmptyFieldException();
        }
        if(destinationBox.getItemAt(indexComboBox).equals("Choose your destination")) {
            flightDestinationStatusLabel.setText("Field cannot be empty");
            throw new EmptyFieldException();
        }
        OkTicketDialog dialog = new OkTicketDialog(data.StaticData.frame, true);
        dialog.setVisible(true);
        data.Client newest = new data.Client(++data.StaticData.nAcc, firstNameField.getText(), lastNameField.getText(), (data.PlaneSchedule) data.StaticData.planeData.search(indexComboBox - 1));
        data.StaticData.clientData.addLast(newest);
        data.StaticData.saveClients();
        this.setVisible(false);
        data.StaticData.loginPanel.setVisible(true);
    }//GEN-LAST:event_ticketBtnActionPerformed

    private void destinationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destinationBox;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameStatusLabel;
    private javax.swing.JLabel flightDestinationLabel;
    private javax.swing.JLabel flightDestinationStatusLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameStatusLabel;
    private javax.swing.JButton ticketBtn;
    // End of variables declaration//GEN-END:variables
}
